# Generated by Django 3.2.9 on 2021-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('title__contains', 't')), name='title_contain_t'),
        ),
    ]
