# Generated by Django 3.2.9 on 2021-11-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_tag_title_contain_t'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='title_contain_t',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('title__contains', 't')), name='post_tag_t_title'),
        ),
    ]
