# Generated by Django 3.2.9 on 2021-11-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20211111_0544'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='post_tag_t_title',
        ),
    ]
