# Generated by Django 3.2.9 on 2021-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_tag_post_tag_t_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('title__contains', 't')), name='post_tag_t_title'),
        ),
    ]
