# Generated by Django 3.2.9 on 2021-11-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_tag_post_tag_t_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='post_tag_t_title',
        ),
    ]
