# Generated by Django 3.2.9 on 2021-11-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20211111_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها '},
        ),
    ]
