# Generated by Django 3.2.9 on 2021-11-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sample',
            field=models.CharField(default='test', max_length=255, verbose_name='title post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
