# Generated by Django 3.2.9 on 2021-11-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20211112_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sample',
        ),
    ]
