# Generated by Django 3.2.9 on 2021-11-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_rename_image_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
