# Generated by Django 3.2.9 on 2021-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
